### ISSUE TITLE
Customize properties on export

### ISSUE THREAD

**Issue by ryanbaumann** [murphy214/nlgeojson#2]
# Problem

make_points() adds extra properties to my geojson export.  I want to be able to explicitly control which properties are exported to minimize the file size of an exported geojson file from a data frame.

# Example

dataframe columns: `lat`, `long`, `mag`, `time`, 'country'

I want to be able to say nl.make_points(df, 'points.geojson', properties=['mag', 'time'] and return a file with the following format:

```json
{
"type": "feature",
"geometry": { "type": "Point", "coordinates": [0,0]},
"properties": {"mag": 2, "time": 1122334455}
}
```
@murphy214

**Comment by murphy214** [comment]
@ryanbaumann 
As per this commit: https://github.com/murphy214/nlgeojson/commit/5e742df49464a952faff522b4b194a333933862c

Requested feature added. Any make function now accepts keep_columns which should be a list of columns to keep all others will be dropped.  Hopefully that works for you!
