### ISSUE TITLE
Control `latitude` and `longitude` dataframe column name mapping

### ISSUE THREAD

**Issue by ryanbaumann** [murphy214/nlgeojson#4]
# Problem

My dataframe may have any column name containing latitude and longitude information.  

# Proposal

Enable user to pass the dataframe column name containing latitude and longitude information into nl.make_points()

@murphy214

**Comment by murphy214** [comment]
@ryanbaumann 
As per this commit: https://github.com/murphy214/nlgeojson/commit/5e742df49464a952faff522b4b194a333933862c

Requested feature added [here](https://github.com/murphy214/nlgeojson/blob/master/nlgeojson/points.py#L16). Hopefully thats what you needed!
